#pragma once

#ifdef USE_ESP32

#include <algorithm>
#include <cerrno>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <unordered_set>
#include <vector>

namespace esphome {
namespace voip_stack {

enum class ContactEndpointType : uint8_t {
  UNKNOWN,
  SIP,
};

inline const char *contact_endpoint_type_to_str(ContactEndpointType endpoint_type) {
  switch (endpoint_type) {
    case ContactEndpointType::SIP:
      return "sip";
    case ContactEndpointType::UNKNOWN:
    default:
      return "unknown";
  }
}

/// One phonebook slot. Empty ip/port = no endpoint yet (name-only placeholder).
/// Phonebook state is SIP-only. The parser still accepts the compact
/// transport-row serialization generated by HA roster sync and ESPHome helper
/// actions; user-facing YAML should use structured contact fields.
/// missing_count tracks consecutive update cycles where this slot was not seen
/// by any source; commit_cycle() advances/resets it and prunes once the
/// configured threshold is hit. Default 0 keeps pruning disabled.
struct ContactEntry {
  std::string name;
  std::string ip;
  ContactEndpointType endpoint_type{ContactEndpointType::UNKNOWN};
  uint16_t port{0};
  uint16_t rtp_port{0};
  bool sip_transport_tcp{false};
  std::string audio_capability;
  uint8_t missing_count{0};
};

/// add_one outcome - lets a batch upload defer publish_* side-effects.
enum class AddResult : uint8_t {
  Noop,
  Added,
  Upgraded,          // name existed without endpoint, now has ip+port
  EndpointReplaced,  // existing endpoint overwritten
  Rejected,          // empty name or self-name
};

/// Local contact list with idempotent merge semantics. Slot order is
/// stable across re-adds so next/prev never jump on republish.
class Phonebook {
 public:
  static constexpr size_t MAX_CONTACTS = 64;
  static constexpr size_t MAX_NAME_BYTES = 64;
  static constexpr size_t MAX_ADDRESS_BYTES = 64;
  static constexpr size_t MAX_CAPABILITY_BYTES = 160;

  /// Skip add_one() for this name (the device's own name).
  void set_self_name(const std::string &n) { this->self_name_ = n; }

  /// Accept one compact transport row. This is an internal serialization used
  /// after structured contacts have already been normalized.
  AddResult add_one(const std::string &entry) {
    ContactEntry incoming;
    if (!parse_entry_(entry, &incoming)) return AddResult::Rejected;
    if (!this->self_name_.empty() && incoming.name == this->self_name_) {
      return AddResult::Rejected;
    }
    return this->merge_(incoming);
  }

  /// Parse one CSV slot without mutating the phonebook. Used by VoipStack to
  /// normalize the HA phonebook into a transport-local dial plan
  /// before merge.
  static bool parse_entry(const std::string &entry, ContactEntry *out) {
    return parse_entry_(entry, out);
  }
  static bool parse_endpoint_type(const std::string &s, ContactEndpointType *out) {
    return parse_endpoint_type_(s, out);
  }
  static bool parse_u16(const std::string &s, uint16_t *out) {
    return parse_u16_(s, out);
  }
  static std::string trim(const std::string &raw) { return trim_(raw); }
  static std::vector<std::string> split(const std::string &s, char sep) {
    return split_(s, sep);
  }

  /// Batch add. True if at least one slot mutated.
  bool add_batch(const std::string &csv) {
    bool changed = false;
    size_t start = 0;
    size_t processed = 0;
    while (start <= csv.size() && processed < MAX_CONTACTS) {
      const size_t comma = csv.find(',', start);
      const size_t end = (comma == std::string::npos) ? csv.size() : comma;
      const AddResult r = this->add_one(csv.substr(start, end - start));
      processed++;
      if (r == AddResult::Added || r == AddResult::Upgraded ||
          r == AddResult::EndpointReplaced) {
        changed = true;
      }
      if (comma == std::string::npos) break;
      start = comma + 1;
    }
    return changed;
  }

  AddResult add_entry(const ContactEntry &entry) {
    if (!this->self_name_.empty() && entry.name == this->self_name_) {
      return AddResult::Rejected;
    }
    return this->merge_(entry);
  }

  /// Replace the entire phonebook from an authoritative typed source while
  /// preserving the selected contact when that name still exists.
  bool replace_all(std::vector<ContactEntry> entries) {
    const std::string selected = this->current_name();
    std::vector<ContactEntry> normalized;
    normalized.reserve(std::min(entries.size(), MAX_CONTACTS));
    for (auto &entry : entries) {
      if (normalized.size() >= MAX_CONTACTS) break;
      if (!valid_entry_(entry)) continue;
      if (!this->self_name_.empty() && entry.name == this->self_name_) continue;
      entry.missing_count = 0;
      bool replaced = false;
      for (auto &existing : normalized) {
        if (existing.name != entry.name) continue;
        existing = std::move(entry);
        replaced = true;
        break;
      }
      if (!replaced) normalized.push_back(std::move(entry));
    }

    const bool changed = !same_entries_(this->entries_, normalized);
    this->entries_ = std::move(normalized);
    this->index_ = 0;
    if (!selected.empty()) this->select(selected);
    return changed;
  }

  /// Drop every entry, reset the cursor.
  void clear() {
    this->entries_.clear();
    this->index_ = 0;
  }

  /// Apply one update-cycle outcome. For each slot: reset missing_count to 0
  /// if its name appears in `seen`, otherwise increment (saturated at 255).
  /// After accounting, prune slots whose missing_count >= threshold.
  /// threshold=0 disables pruning entirely (counters still advance, no prune).
  /// Cursor is preserved via remove_one() which shifts/wraps as needed.
  /// Returns true if at least one slot was removed (caller should re-publish).
  bool commit_cycle(const std::unordered_set<std::string> &seen, uint8_t threshold) {
    for (auto &entry : this->entries_) {
      if (seen.count(entry.name)) {
        entry.missing_count = 0;
      } else if (entry.missing_count < 255) {
        entry.missing_count++;
      }
    }
    if (threshold == 0) return false;
    std::vector<std::string> to_remove;
    for (const auto &entry : this->entries_) {
      if (entry.missing_count >= threshold) to_remove.push_back(entry.name);
    }
    bool changed = false;
    for (const auto &name : to_remove) {
      if (this->remove_one(name)) changed = true;
    }
    return changed;
  }

  /// Cursor follows: removing before the cursor shifts it down; removing
  /// the cursor itself keeps it on the next slot (or wraps to 0).
  bool remove_one(const std::string &name) {
    for (size_t i = 0; i < this->entries_.size(); i++) {
      if (this->entries_[i].name != name) continue;
      this->entries_.erase(this->entries_.begin() + i);
      if (this->entries_.empty()) {
        this->index_ = 0;
      } else if (i < this->index_) {
        this->index_--;
      } else if (i == this->index_ && this->index_ >= this->entries_.size()) {
        this->index_ = 0;
      }
      return true;
    }
    return false;
  }

  /// Move the cursor to the named contact. Returns false if not present.
  bool select(const std::string &name) {
    for (size_t i = 0; i < this->entries_.size(); i++) {
      if (this->entries_[i].name == name) {
        this->index_ = i;
        return true;
      }
    }
    return false;
  }

  /// Step through positions in order. No-op on empty phonebook.
  void next() {
    if (this->entries_.empty()) return;
    this->index_ = (this->index_ + 1) % this->entries_.size();
  }
  void prev() {
    if (this->entries_.empty()) return;
    this->index_ = (this->index_ + this->entries_.size() - 1) % this->entries_.size();
  }

  const ContactEntry *current() const {
    if (this->entries_.empty()) return nullptr;
    return &this->entries_[this->index_ % this->entries_.size()];
  }

  /// Lookup without moving the cursor (safe on the FSM hot path).
  const ContactEntry *find(const std::string &name) const {
    for (const auto &e : this->entries_) {
      if (e.name == name) return &e;
    }
    return nullptr;
  }
  const std::string &current_name() const {
    static const std::string kEmpty;
    const auto *c = this->current();
    return c ? c->name : kEmpty;
  }
  const std::string &current_ip() const {
    static const std::string kEmpty;
    const auto *c = this->current();
    return c ? c->ip : kEmpty;
  }
  uint16_t current_port() const {
    const auto *c = this->current();
    return c ? c->port : 0;
  }
  ContactEndpointType current_endpoint_type() const {
    const auto *c = this->current();
    return c ? c->endpoint_type : ContactEndpointType::UNKNOWN;
  }

  /// Comma-separated list of names (no endpoints) for diagnostic publishing.
  std::string names_csv() const {
    std::string out;
    for (size_t i = 0; i < this->entries_.size(); i++) {
      if (i > 0) out.push_back(',');
      out += this->entries_[i].name;
    }
    return out;
  }

  size_t size() const { return this->entries_.size(); }
  bool empty() const { return this->entries_.empty(); }
  size_t cursor() const { return this->index_; }

 protected:
  /// Dedup by name; on endpoint conflict the last writer wins. HA is the
  /// authority for cross-device SIP routing, including cross-transport peers.
  /// DHCP IP changes resolve on the next batch.
  AddResult merge_(const ContactEntry &incoming) {
    if (!valid_entry_(incoming)) return AddResult::Rejected;
    for (auto &existing : this->entries_) {
      if (existing.name != incoming.name) continue;
      if (incoming.ip.empty() && incoming.port == 0 && incoming.rtp_port == 0) {
        return AddResult::Noop;
      }
      if (existing.ip == incoming.ip && existing.port == incoming.port &&
          existing.rtp_port == incoming.rtp_port &&
          existing.endpoint_type == incoming.endpoint_type &&
          existing.sip_transport_tcp == incoming.sip_transport_tcp &&
          existing.audio_capability == incoming.audio_capability) {
        return AddResult::Noop;
      }
      const bool was_unset = existing.ip.empty() && existing.port == 0 &&
                             existing.rtp_port == 0;
      existing.ip = incoming.ip;
      existing.endpoint_type = incoming.endpoint_type;
      existing.port = incoming.port;
      existing.rtp_port = incoming.rtp_port;
      existing.sip_transport_tcp = incoming.sip_transport_tcp;
      existing.audio_capability = incoming.audio_capability;
      return was_unset ? AddResult::Upgraded : AddResult::EndpointReplaced;
    }
    // New name: append; cursor unchanged so the UI doesn't jump.
    if (this->entries_.size() >= MAX_CONTACTS) return AddResult::Rejected;
    this->entries_.push_back(incoming);
    return AddResult::Added;
  }

  static bool same_entry_(const ContactEntry &a, const ContactEntry &b) {
    return a.name == b.name && a.ip == b.ip && a.endpoint_type == b.endpoint_type &&
           a.port == b.port && a.rtp_port == b.rtp_port &&
           a.sip_transport_tcp == b.sip_transport_tcp &&
           a.audio_capability == b.audio_capability;
  }

  static bool same_entries_(const std::vector<ContactEntry> &a,
                            const std::vector<ContactEntry> &b) {
    if (a.size() != b.size()) return false;
    for (size_t i = 0; i < a.size(); i++) {
      if (!same_entry_(a[i], b[i])) return false;
    }
    return true;
  }

  static bool parse_entry_(const std::string &raw, ContactEntry *out) {
    const std::string s = trim_(raw);
    if (s.empty()) return false;

    const std::vector<std::string> parts = split_(s, '|');
    if (parts.empty()) return false;

    ContactEntry c;
    c.name = trim_(parts[0]);
    if (c.name.empty()) return false;

    if (!parse_short_entry_(parts, &c)) return false;
    if (!valid_entry_(c)) return false;

    *out = std::move(c);
    return true;
  }

  static bool parse_short_entry_(const std::vector<std::string> &parts, ContactEntry *out) {
    if (parts.size() == 1) return true;
    if (parts.size() != 5 && parts.size() != 8) return false;
    out->endpoint_type = ContactEndpointType::SIP;
    out->ip = trim_(parts[1]);
    if (out->ip.empty()) return false;
    if (!parse_u16_(trim_(parts[2]), &out->port) ||
        !parse_u16_(trim_(parts[3]), &out->rtp_port)) {
      return false;
    }
    const size_t transport_index = parts.size() == 8 ? 7 : 4;
    if (parts.size() == 8) out->audio_capability = trim_(parts[4]);
    const std::string transport = trim_(parts[transport_index]);
    if (transport == "sip_tcp" || transport == "SIP_TCP") {
      out->sip_transport_tcp = true;
      return true;
    }
    if (transport == "sip_udp" || transport == "SIP_UDP") {
      out->sip_transport_tcp = false;
      return true;
    }
    return false;
  }

  static bool parse_endpoint_type_(const std::string &s, ContactEndpointType *out) {
    if (s == "sip" || s == "SIP") {
      *out = ContactEndpointType::SIP;
      return true;
    }
    return false;
  }

  static std::string trim_(const std::string &raw) {
    size_t begin = 0;
    while (begin < raw.size() && (raw[begin] == ' ' || raw[begin] == '\t')) begin++;
    size_t end = raw.size();
    while (end > begin && (raw[end - 1] == ' ' || raw[end - 1] == '\t')) end--;
    return raw.substr(begin, end - begin);
  }

  static std::vector<std::string> split_(const std::string &s, char sep) {
    std::vector<std::string> out;
    out.reserve(8);
    size_t start = 0;
    while (start <= s.size() && out.size() < MAX_CONTACTS) {
      const size_t pos = s.find(sep, start);
      if (pos == std::string::npos) {
        out.push_back(s.substr(start));
        break;
      }
      out.push_back(s.substr(start, pos - start));
      start = pos + 1;
    }
    return out;
  }

  static bool parse_u16_(const std::string &s, uint16_t *out) {
    if (s.empty()) return false;
    char *end = nullptr;
    errno = 0;
    unsigned long value = std::strtoul(s.c_str(), &end, 10);
    if (errno != 0 || end == s.c_str() || *end != '\0' || value > 65535UL) {
      return false;
    }
    *out = static_cast<uint16_t>(value);
    return true;
  }

  static bool valid_text_field_(const std::string &value, size_t max_bytes,
                                bool reject_list_delimiters) {
    if (value.size() > max_bytes) return false;
    for (char ch : value) {
      if (static_cast<unsigned char>(ch) < 0x20 || static_cast<unsigned char>(ch) == 0x7F || ch == '|' ||
          (reject_list_delimiters && (ch == ',' || ch == ';'))) {
        return false;
      }
    }
    return true;
  }

  static bool valid_entry_(const ContactEntry &entry) {
    if (entry.name.empty() ||
        !valid_text_field_(entry.name, MAX_NAME_BYTES, true) ||
        !valid_text_field_(entry.ip, MAX_ADDRESS_BYTES, true) ||
        !valid_text_field_(entry.audio_capability, MAX_CAPABILITY_BYTES, true)) {
      return false;
    }
    if (entry.endpoint_type == ContactEndpointType::SIP) {
      return !entry.ip.empty() && entry.port != 0;
    }
    return entry.endpoint_type == ContactEndpointType::UNKNOWN && entry.ip.empty() &&
           entry.port == 0 && entry.rtp_port == 0;
  }

  std::vector<ContactEntry> entries_;
  size_t index_{0};
  std::string self_name_;

};

}  // namespace voip_stack
}  // namespace esphome

#endif  // USE_ESP32
